create database PixFourFun;

CREATE TABLE Usuario(
	IdUsuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE Cupom(
	IdCupom INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE Fotos(
	IdFotos INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE Pack(
	IdPack  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (IdFotos) REFERENCES Fotos(IdFotos)
);

CREATE TABLE Pagamento(
	IdPagamento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (IdUsuarios) REFERENCES Usuarios(IdUsuarios)
);

CREATE TABLE Pedido(
	IdPedido INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (IdUsuarios) REFERENCES Usuarios(IdUsuarios),
    FOREIGN KEY (IdPack) REFERENCES Pack(IdPack),
	FOREIGN KEY (IdCupom) REFERENCES Cupom(IdCupom)
    
);


